export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SETECT_JEWELERY:"SETECT_JEWELERY",
  SETECT_MEN:"SETECT_MEN",
  SETECT_WOMEN:"SETECT_WOMEN",
  SETECT_ELECTRONICS:"SETECT_ELECTRONICS",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_FROM_CART:"REMOVE_FROM_CART",
  SETECT_RATING:"SETECT_RATING",
  SETECT_PRICE:"SETECT_PRICE",
  PRICE_HIGH_TO_LOW:"PRICE_HIGH_TO_LOW",
  PRICE_LOW_TO_HIGH:"PRICE_LOW_TO_HIGH",
  CHANGE_QYT:"CHANGE_QYT",
  INCREASE_QYT:"INCREASE_QYT",
  DECREASE_QYT:"DECREASE_QYT"
};
