export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SETECT_JEWELERY:"SETECT_JEWELERY",
  SETECT_MEN:"SETECT_MEN",
  SETECT_WOMEN:"SETECT_WOMEN",
  SETECT_ELECTRONICS:"SETECT_ELECTRONICS",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_FROM_CART:"REMOVE_FROM_CART"
};
